# Adatbázis kapcsolat
spring.datasource.url=jdbc:postgresql://localhost:5432/egyetemkapu
spring.datasource.username=postgres
spring.datasource.password=admin1234

# Hibernate (JPA) beállítások
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true