CREATE TABLE flyers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    official_url VARCHAR(1000) NOT NULL,
    pdf_url VARCHAR(1000),
    source_key VARCHAR(255) NOT NULL UNIQUE,
    valid_from DATE,
    valid_to DATE,
    last_synced TIMESTAMP(6) NOT NULL
);

CREATE TABLE flyer_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flyer_id BIGINT NOT NULL REFERENCES flyers(id) ON DELETE CASCADE,
    page_number INT NOT NULL,
    image_url VARCHAR(2000),
    page_text TEXT,
    UNIQUE (flyer_id, page_number)
);

CREATE TABLE flyer_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flyer_id BIGINT NOT NULL REFERENCES flyers(id) ON DELETE CASCADE,
    page_number INT NOT NULL,
    name VARCHAR(500) NOT NULL,
    price_text VARCHAR(255),
    image_url VARCHAR(2000)
);

CREATE INDEX idx_flyers_store ON flyers(store);
CREATE INDEX idx_flyer_products_flyer ON flyer_products(flyer_id);
CREATE INDEX idx_flyer_pages_flyer ON flyer_pages(flyer_id);
