CREATE TABLE flashcard_decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_flashcard_decks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_flashcard_decks_user ON flashcard_decks (user_id);

CREATE TABLE flashcards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL,
    front VARCHAR(1000) NOT NULL,
    back VARCHAR(1000) NOT NULL,
    interval_days INTEGER NOT NULL,
    due_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_flashcards_deck FOREIGN KEY (deck_id) REFERENCES flashcard_decks (id) ON DELETE CASCADE
);

CREATE INDEX idx_flashcards_deck_due ON flashcards (deck_id, due_at);
