ALTER TABLE tasks 
ADD COLUMN ping_telegram_day_before BOOLEAN DEFAULT FALSE NOT NULL,
ADD COLUMN ping_telegram_on_day BOOLEAN DEFAULT FALSE NOT NULL,
ADD COLUMN user_id BIGINT;

ALTER TABLE tasks
ADD CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_webhook VARCHAR(255),
    telegram_chat_id VARCHAR(255),
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_settings_user FOREIGN KEY (user_id) REFERENCES users (id)
);